<?php

/**
 * ALgerian Cities
 * @author   Embarek MESSAI <m_mebarek@hotmail.com>
 * @version  1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $citie;

$citie['DZ'] = array(
    "ADR" => array(
        "Adrar",
        "Bouda",
        "Ouled Ahmed Timmi",
        "Aougrout",
        "Deldoul",
        "Metarfa",
        "Akabli",
        "Aoulef",
        "Timekten",
        "Tit",
        "Bordj Badji Mokhtar",
        "Timiaouine",
        "Charouine",
        "Ouled Aissa",
        "Talmine",
        "Fenoughil",
        "Tamantit",
        "Tamest",
        "Reggane",
        "Sali",
        "Ouled Said",
        "Timimoun",
        "Ksar Kaddour",
        "Tinerkouk",
        "Sebaa",
        "Tsabit",
        "In Zghmir",
        "Zaouiet Kounta"
    ),

    "CHL" => array(
        "Abou El Hassane",
        "Tadjena",
        "Talassa",
        "Ain Merane",
        "Herenfa",
        "Beni Haoua",
        "Breira",
        "Oued Goussine",
        "Boukadir",
        "Oued Sly",
        "Sobha",
        "Chlef",
        "Oum Drou",
        "Sendjas",
        "Beni  Bouattab",
        "El Karimia",
        "Harchoun",
        "El Marsa",
        "Moussadek",
        "Beni Rached",
        "Oued Fodda",
        "Ouled Abbes",
        "El Hadjadj",
        "Ouled Ben Abdelkader",
        "Chettia",
        "Labiod Medjadja",
        "Ouled Fares",
        "Dahra",
        "Taougrit",
        "Sidi Abderrahmane",
        "Sidi Akkacha",
        "Tenes",
        "Benairia",
        "Bouzeghaia",
        "Zeboudja"
    ),

    "LAG" => array(
        "Aflou",
        "Sebgag",
        "Sidi Bouzid",
        "Ain Madhi",
        "El Haouaita",
        "Kheneg",
        "Tadjemout",
        "Tadjrouna",
        "Brida",
        "Hadj Mechri",
        "Taouiala",
        "El Ghicha",
        "Ain Sidi Ali",
        "El Beidha",
        "Gueltat Sidi Saad",
        "Hassi Delaa",
        "Hassi R'mel",
        "Benacer Benchohra",
        "Ksar El Hirane",
        "Laghouat",
        "Oued Morra",
        "Oued M'zi",
        "El Assafia",
        "Sidi Makhlouf"
    ),

    "OMB" => array(
        "Ain Babouche",
        "Ain Diss",
        "Ain Beida",
        "Berriche",
        "Zorg",
        "Ain Fekroun",
        "El Fedjoudj Boughrara Sa",
        "Ain Kercha",
        "El Harmilia",
        "Hanchir Toumghani",
        "Ain M'lila",
        "Ouled Gacem",
        "Ouled Hamla",
        "Dhalaa",
        "El Djazia",
        "Fkirina",
        "Oued Nini",
        "Ksar Sbahi",
        "Behir Chergui",
        "El Belala",
        "Meskiana",
        "Rahia",
        "Ain Zitoun",
        "Oum El Bouaghi",
        "El Amiria",
        "Sigus",
        "Bir Chouhada",
        "Ouled Zouai",
        "Souk Naamane"
    ),
    
    "BTN" => array(
        "Ain Djasser",
        "El Hassi",
        "Ain Touta",
        "Beni Foudhala El Hakania",
        "Maafa",
        "Ouled Aouf",
        "Arris",
        "Tighanimine",
        "Barika",
        "Bitam",
        "M Doukal",
        "Batna",
        "Fesdis",
        "Oued Chaaba",
        "Bouzina",
        "Larbaa",
        "Boulhilat",
        "Chemora",
        "Azil Abedelkader",
        "Djezzar",
        "Ouled Ammar",
        "Ain Yagout",
        "Boumia",
        "Djerma",
        "El Madher",
        "Foum Toub",
        "Ichemoul",
        "Inoughissen",
        "Menaa",
        "Tigharghar",
        "Hidoussa",
        "Ksar Bellezma",
        "Merouana",
        "Oued El Ma",
        "Boumagueur",
        "N Gaous",
        "Sefiane",
        "Lemcene",
        "Ouled Si Slimane",
        "Taxlent",
        "Gosbat",
        "Guigba",
        "Ouled Sellem",
        "Rahbat",
        "Ras El Aioun",
        "Talkhamt",
        "Seggana",
        "Tilatou",
        "Lazrou",
        "Seriana",
        "Zanet El Beida",
        "Ouyoun El Assafir",
        "Tazoult",
        "Chir",
        "Oued Taga",
        "Teniet El Abed",
        "Ouled Fadel",
        "Timgad",
        "Ghassira",
        "Kimmel",
        "T Kout"
    ),

    "BJA" => array(
        "Adekar",
        "Beni K'sila",
        "Taourit Ighil",
        "Akbou",
        "Chellata",
        "Ighram",
        "Tamokra",
        "Amizour",
        "Beni Djellil",
        "Feraoun",
        "Smaoun",
        "Aokas",
        "Tizi-N'berber",
        "Barbacha",
        "Kendira",
        "Bejaia",
        "Oued Ghir",
        "Benimaouche",
        "Akfadou",
        "Chemini",
        "Souk Oufella",
        "Tibane",
        "Ait-Smail",
        "Darguina",
        "Taskriout",
        "El Kseur",
        "Fenaia Il Maten",
        "Toudja",
        "Ouzellaguen",
        "Ait R'zine",
        "Ighil-Ali",
        "Dra El Caid",
        "Kherrata",
        "Amalou",
        "Bouhamza",
        "M'cisna",
        "Seddouk",
        "Leflaye",
        "Sidi Ayad",
        "Sidi-Aich",
        "Tifra",
        "Tinebdar",
        "Melbou",
        "Souk El Tenine",
        "Tamridjet",
        "Beni-Mallikeche",
        "Boudjellil",
        "Tazmalt",
        "Boukhelifa",
        "Tala Hamza",
        "Tichy",
        "Timezrit"
    ),

    "BSK" => array(
        "Biskra",
        "El Hadjab",
        "Branis",
        "Djemorah",
        "Ain Zaatout",
        "El Kantara",
        "El Outaya",
        "El Ghrous",
        "Foughala",
        "M'chouneche",
        "Chaiba",
        "Doucen",
        "Ouled Djellal",
        "Lioua",
        "Mekhadma",
        "M'lili",
        "Oumache",
        "Ourlal",
        "Besbes",
        "Ras El Miad",
        "Sidi Khaled",
        "Ain Naga",
        "Chetma",
        "El Haouch",
        "Sidi Okba",
        "Bordj Ben Azzouz",
        "Bouchakroun",
        "Lichana",
        "Tolga",
        "El Feidh",
        "Khenguet Sidi Nadji",
        "Meziraa",
        "Zeribet El Oued"
    ),

    "BCH" => array(
        "Abadla",
        "Erg-Ferradj",
        "Machraa-Houari-Boumediene",
        "Bechar",
        "Beni-Abbes",
        "Tamtert",
        "Beni-Ounif",
        "El Ouata",
        "Igli",
        "Kenadsa",
        "Meridja",
        "Beni-Ikhlef",
        "Kerzaz",
        "Timoudi",
        "Boukais",
        "Lahmar",
        "Mogheul",
        "Ksabi",
        "Ouled-Khodeir",
        "Tabelbala",
        "Taghit"
    ),

    "BLD" => array(
        "Blida",
        "Bouarfa",
        "Boufarik",
        "Guerrouaou",
        "Soumaa",
        "Bougara",
        "Hammam Elouane",
        "Ouled Slama",
        "Bouinan",
        "Chebli",
        "El-Affroun",
        "Oued  Djer",
        "Larbaa",
        "Souhane",
        "Djebabra",
        "Meftah",
        "Ain Romana",
        "Chiffa",
        "Mouzaia",
        "Beni-Tamou",
        "Benkhelil",
        "Oued El Alleug",
        "Beni Mered",
        "Chrea",
        "Ouled Yaich"
    ),

    "BRA" => array(
        "Ain El Hadjar",
        "Ain Laloui",
        "Ain-Bessem",
        "Ahl El Ksar",
        "Bechloul",
        "El Adjiba",
        "El Asnam",
        "Ouled Rached",
        "Bir Ghbalou",
        "El Khabouzia",
        "Raouraoua",
        "Bordj Okhriss",
        "Hadjera Zerga",
        "Mezdour",
        "Taguedite",
        "Ain Turk",
        "Ait Laaziz",
        "Bouira",
        "El Hachimia",
        "Oued El Berdi",
        "Haizer",
        "Taghzout",
        "Aomar",
        "Djebahia",
        "Kadiria",
        "Bouderbala",
        "Boukram",
        "Guerrouma",
        "Lakhdaria",
        "Maala",
        "Z'barbar (El Isseri )",
        "Aghbalou",
        "Chorfa",
        "Hanif",
        "M Chedallah",
        "Saharidj",
        "Ath Mansour",
        "El-Mokrani",
        "Souk El Khemis",
        "Dechmia",
        "Dirah",
        "El-Hakimia",
        "Maamora",
        "Ridane",
        "Sour El Ghozlane"
    ),

    "TAM" => array(
        "Inghar",
        "Ain Guezzam",
        "Ain Salah",
        "Foggaret Ezzoua",
        "Abelsa",
        "Ain Amguel",
        "Tamanrasset",
        "Idles",
        "Tazrouk",
        "Tin Zouatine"
    ),

    "TBS" => array(
        "Bir-El-Ater",
        "El Ogla El Malha",
        "Bir Mokkadem",
        "Guorriguer",
        "Hammamet",
        "Cheria",
        "Telidjen",
        "Boukhadra",
        "El-Aouinet",
        "Bekkaria",
        "Boulhaf Dyr",
        "El Kouif",
        "El Malabiod",
        "El-Houidjbet",
        "Bedjene",
        "El Mezeraa",
        "El Ogla",
        "Stah Guentis",
        "Bir Dheheb",
        "Morsott",
        "Ferkane",
        "Negrine",
        "Ain Zerga",
        "El Meridj",
        "Ouenza",
        "Oum Ali",
        "Saf Saf El Ouesra",
        "Tebessa"
    ),

    "TLM" => array(
        "Ain Nehala",
        "Ain Tellout",
        "Bab El Assa",
        "Souani",
        "Souk Tleta",
        "Beni Boussaid",
        "Sidi Medjahed",
        "Beni Bahdel",
        "Beni Snous",
        "Azail",
        "Bensekrane",
        "Sidi Abdelli",
        "Ain Fezza",
        "Amieur",
        "Chetouane",
        "Ain Fetah",
        "Ain Kebira",
        "Fellaoucene",
        "Dar Yaghmoracen",
        "Ghazaouet",
        "Souahlia",
        "Tianet",
        "Hennaya",
        "Ouled Riyah",
        "Zenata",
        "Beni Khellad",
        "Honnaine",
        "Hammam Boughrara",
        "Maghnia",
        "Ain Ghoraba",
        "Beni Mester",
        "Mansourah",
        "Terny Beni Hediel",
        "Marsa Ben M'hidi",
        "M'sirda Fouaga",
        "Djebala",
        "Nedroma",
        "Beni Smiel",
        "Oued Lakhdar",
        "Ouled Mimoun",
        "Ain Youcef",
        "Beni Ouarsous",
        "El Fehoul",
        "Remchi",
        "Sebbaa Chioukh",
        "Bouhlou",
        "Sabra",
        "El Aricha",
        "El Gor",
        "Sebdou",
        "Bouihi",
        "Sidi Djillali",
        "Tlemcen"
    ),

    "TIR" => array(
        "Ain Deheb",
        "Chehaima",
        "Naima",
        "Ain Kermes",
        "Djebilet Rosfa",
        "Madna",
        "Medrissa",
        "Sidi Abderrahmane",
        "Ain Bouchekif",
        "Dahmouni",
        "Ain El Hadid",
        "Frenda",
        "Takhemaret",
        "Bougara",
        "Hamadia",
        "Rechaiga",
        "Ksar Chellala",
        "Serghine",
        "Zmalet El Emir Abdelkade",
        "Ain Dzarit",
        "Mahdia",
        "Nadorah",
        "Sebaine",
        "Djillali Ben Amar",
        "Mechraa Safa",
        "Tagdempt",
        "Medroussa",
        "Mellakou",
        "Sidi Bakhti",
        "Meghila",
        "Sebt",
        "Sidi Hosni",
        "Oued Lilli",
        "Sidi Ali Mellal",
        "Tidda",
        "Guertoufa",
        "Rahouia",
        "Faidja",
        "Si Abdelghani",
        "Sougueur",
        "Tousnina",
        "Tiaret"
    ),

    "TIZ" => array(
        "Abi-Youcef",
        "Ain-El-Hammam",
        "Ait-Yahia",
        "Akbil",
        "Azazga",
        "Freha",
        "Ifigha",
        "Yakourene",
        "Zekri",
        "Aghribs",
        "Ait-Chafaa",
        "Akerrou",
        "Azeffoun",
        "Ait-Mahmoud",
        "Beni Zmenzer",
        "Beni-Aissi",
        "Beni-Douala",
        "Beni-Yenni",
        "Iboudrarene",
        "Yatafene",
        "Assi-Youcef",
        "Boghni",
        "Bounouh",
        "Mechtras",
        "Beni-Zikki",
        "Bouzeguene",
        "Idjeur",
        "Illoula Oumalou",
        "Draa-Ben-Khedda",
        "Sidi Namane",
        "Tadmait",
        "Tirmitine",
        "Ain-Zaouia",
        "Ait Yahia Moussa",
        "Draa-El-Mizan",
        "Frikat",
        "Iferhounene",
        "Illilten",
        "Imsouhal",
        "Ait Aggouacha",
        "Irdjen",
        "Larbaa Nath Irathen",
        "Maatkas",
        "Souk-El-Tenine",
        "Boudjima",
        "Makouda",
        "Ait Khellili",
        "Mekla",
        "Souama",
        "Ait Boumahdi",
        "Ait-Toudert",
        "Ouacif",
        "Agouni-Gueghrane",
        "Ait Bouaddou",
        "Ouadhias",
        "Tizi N'tleta",
        "Ait-Aissa-Mimoun",
        "Ouaguenoun",
        "Timizart",
        "Iflissen",
        "Mizrana",
        "Tigzirt",
        "Tizi-Ouzou",
        "Ait-Oumalou",
        "Tizi-Rached",
        "M'kira",
        "Tizi-Gheniff"
    ),

    "ALG" => array(
        "Bab El Oued",
        "Bologhine Ibnou Ziri",
        "Casbah",
        "Oued Koriche",
        "Rais Hamidou",
        "Baraki",
        "Les Eucalyptus",
        "Sidi Moussa",
        "Bir Mourad Rais",
        "Birkhadem",
        "Djasr Kasentina",
        "Hydra",
        "Sehaoula",
        "Bir Touta",
        "Ouled Chebel",
        "Tessala El Merdja",
        "Ben Aknoun",
        "Beni Messous",
        "Bouzareah",
        "El Biar",
        "Ain Benian",
        "Cheraga",
        "Dely Ibrahim",
        "Hammamet",
        "Ouled Fayet",
        "Ain Taya",
        "Bab Ezzouar",
        "Bordj El Bahri",
        "Bordj El Kiffan",
        "Dar El Beida",
        "El Marsa",
        "Mohammadia",
        "Baba Hassen",
        "Douira",
        "Draria",
        "El Achour",
        "Khraissia",
        "Bachedjerah",
        "Bourouba",
        "El Harrach",
        "Oued Smar",
        "El Magharia",
        "Hussein Dey",
        "Kouba",
        "Mohamed Belouzdad",
        "Herraoua",
        "Reghaia",
        "Rouiba",
        "Alger Centre",
        "El Madania",
        "El Mouradia",
        "Sidi M'hamed",
        "Maalma",
        "Rahmania",
        "Souidania",
        "Staoueli",
        "Zeralda"
    ),

    "DJL" => array(
        "Ain El Ibel",
        "Moudjebara",
        "Taadmit",
        "Zaccar",
        "Ain Oussera",
        "Guernini",
        "Benhar",
        "Birine",
        "Benyagoub",
        "Charef",
        "El Guedid",
        "Dar Chioukh",
        "M'liliha",
        "Sidi Baizid",
        "Djelfa",
        "Ain Chouhada",
        "Douis",
        "El Idrissia",
        "Amourah",
        "Faidh El Botma",
        "Oum Laadham",
        "Ain Fekka",
        "Bouira Lahdab",
        "Had Sahary",
        "Ain Maabed",
        "Hassi Bahbah",
        "Hassi El Euch",
        "Zaafrane",
        "Deldoul",
        "Guettara",
        "Messaad",
        "Sed Rahal",
        "Selmana",
        "El Khemis",
        "Hassi Fedoul",
        "Sidi Laadjel"
    ),

    "JIJ" => array(
        "Bordj T'har",
        "Chekfa",
        "El Kennar Nouchfi",
        "Sidi Abdelaziz",
        "Boudria Beniyadjis",
        "Djimla",
        "Bouraoui Belhadef",
        "Djemaa Beni Habibi",
        "El Ancer",
        "Khiri Oued Adjoul",
        "El Aouana",
        "Selma Benziada",
        "El Milia",
        "Ouled Yahia Khadrouch",
        "Jijel",
        "Ghebala",
        "Settara",
        "Ouled Rabah",
        "Sidi Marouf",
        "Boussif Ouled Askeur",
        "Chahna",
        "Emir Abdelkader",
        "Oudjana",
        "Taher",
        "Kaous",
        "Texenna",
        "Erraguene Souissi",
        "Ziama Mansouriah"
    ),

    "SET" => array(
        "Ain Abessa",
        "Ain Arnat",
        "El Ouricia",
        "Mezloug",
        "Ain Azel",
        "Ain Lahdjar",
        "Beidha Bordj",
        "Bir Haddada",
        "Ain El Kebira",
        "Dehamcha",
        "Ouled Addouane",
        "Ain Oulmene",
        "Guellal",
        "Kasr El Abtal",
        "Ouled Si Ahmed",
        "Amoucha",
        "Oued El Bared",
        "Tizi N'bechar",
        "Babor",
        "Serdj-El-Ghoul",
        "Ain-Sebt",
        "Beni-Aziz",
        "Maaouia",
        "Ain-Legradj",
        "Beni Chebana",
        "Beni Ourtilane",
        "Beni-Mouhli",
        "Bellaa",
        "Bir-El-Arch",
        "El-Ouldja",
        "Tachouda",
        "Ait Naoual Mezada",
        "Ait-Tizi",
        "Bouandas",
        "Bousselam",
        "Ain-Roua",
        "Beni Oussine",
        "Bougaa",
        "Beni Fouda",
        "Djemila",
        "Bazer-Sakra",
        "El Eulma",
        "Guelta Zerka",
        "Guenzet",
        "Harbil",
        "Guidjel",
        "Ouled Sabor",
        "Draa-Kebila",
        "Hammam Guergour",
        "Hamam Soukhna",
        "Taya",
        "Tella",
        "Maouaklane",
        "Tala-Ifacene",
        "Boutaleb",
        "Hamma",
        "Ouled Tebben",
        "Rosfa",
        "Salah Bey",
        "Setif"
    ),

    "SAI" => array(
        "Ain El Hadjar",
        "Moulay Larbi",
        "Sidi Ahmed",
        "Ain Sekhouna",
        "El Hassasna",
        "Maamora",
        "Ain Soltane",
        "Ouled Brahim",
        "Tircine",
        "Saida",
        "Hounet",
        "Ouled Khaled",
        "Sidi Amar",
        "Sidi Boubekeur",
        "Doui Thabet",
        "Youb"
    ),

    "SKI" => array(
        "Ain Kechra",
        "Ouldja Boulbalout",
        "Ain Charchar",
        "Azzaba",
        "Djendel Saadi Mohamed",
        "El Ghedir",
        "Es Sebt",
        "Bekkouche Lakhdar",
        "Ben Azzouz",
        "El Marsa",
        "Beni Zid",
        "Cheraia",
        "Collo",
        "Ain Zouit",
        "Bouchetata",
        "El Hadaiek",
        "El Arrouch",
        "Emjez Edchich",
        "Ouled Habbaba",
        "Salah Bouchaour",
        "Zerdezas",
        "Khenag Maoune",
        "Oued Zhour",
        "Ouled Attia",
        "Oum Toub",
        "Beni Bechir",
        "Ramdane Djamel",
        "Ain Bouziane",
        "Beni Oulbane",
        "Sidi Mezghiche",
        "Filfila",
        "Hammadi Krouma",
        "Skikda",
        "Bin El Ouiden",
        "Kerkara",
        "Tamalous",
        "Kanoua",
        "Zitouna",
    ),

    "SBA" => array(
        "Ain El Berd",
        "Makedra",
        "Sidi Brahim",
        "Sidi Hamadouche",
        "Bedrabine El Mokrani",
        "Ben Badis",
        "Chetouane Belaila",
        "Hassi Zahana",
        "Bir El Hammam",
        "Marhoum",
        "Sidi Chaib",
        "Merine",
        "Oued Taourira",
        "Taoudmout",
        "Tefessour",
        "Belarbi",
        "Mostefa  Ben Brahim",
        "Tilmouni",
        "Zerouala",
        "Ain Tindamine",
        "El Hacaiba",
        "Moulay Slissen",
        "Oued Sebaa",
        "Ras El Ma",
        "Redjem Demouche",
        "Ain- Adden",
        "Boudjebaa El Bordj",
        "M'cid",
        "Sfisef",
        "Boukhanefis",
        "Sidi Ali Benyoub",
        "Tabia",
        "Ain Kada",
        "Lamtar",
        "Sidi Ali Boussidi",
        "Sidi Dahou Zairs",
        "Sidi Bel-Abbes",
        "Amarnas",
        "Sidi Khaled",
        "Sidi Lahcene",
        "Sidi Yacoub",
        "Dhaya",
        "Mezaourou",
        "Teghalimet",
        "Telagh",
        "Benachiba Chelia",
        "Hassi Dahou",
        "Oued Sefioun",
        "Tenira",
        "Ain Thrid",
        "Sehala Thaoura",
        "Tessala"
    ),

    "ANB" => array(
        "Ain El Berda",
        "Cheurfa",
        "El Eulma",
        "Annaba",
        "Seraidi",
        "Berrahal",
        "Oued El Aneb",
        "Treat",
        "Chetaibi",
        "El Bouni",
        "El Hadjar",
        "Sidi Amar"
    ),

    "GUE" => array(
        "Medjez Amar",
        "Houari Boumedienne",
        "Ras El Agba",
        "Sellaoua Announa",
        "Ain Larbi",
        "Ain Makhlouf",
        "Tamlouka",
        "Ain Ben Beida",
        "Bouchegouf",
        "Medjez Sfa",
        "Oued Ferragha",
        "Belkheir",
        "Beni Mezline",
        "Boumahra Ahmed",
        "Djeballah Khemissi",
        "Guelaat Bou Sbaa",
        "Nechmaya",
        "Bendjarah",
        "Guelma",
        "Bou Hamdane",
        "Hammam Debagh",
        "Roknia",
        "Dahouara",
        "Hammam N'bail",
        "Oued Cheham",
        "Bouati Mahmoud",
        "El Fedjoudj",
        "Heliopolis",
        "Ain Sandel",
        "Bou Hachana",
        "Khezaras",
        "Ain Regada",
        "Bordj Sabath",
        "Oued Zenati"
    ),

    "CON" => array(
        "Ain Abid",
        "Ben Badis",
        "Constantine",
        "Ain Smara",
        "El Khroub",
        "Ouled Rahmoun",
        "Didouche Mourad",
        "Hamma Bouziane",
        "Ibn Ziad",
        "Messaoud Boudjeriou",
        "Beni Hamidane",
        "Zighoud Youcef"
    ),

    "MED" => array(
        "Ain Boucif",
        "El Ouinet",
        "Kef Lakhdar",
        "Ouled Emaaraf",
        "Sidi Demed",
        "Aziz",
        "Derrag",
        "Oum El Djellil",
        "Beni Slimane",
        "Bouskene",
        "Sidi Rabie",
        "Berrouaghia",
        "Ouled Deid",
        "Rebaia",
        "Bouaiche",
        "Boughzoul",
        "Chabounia",
        "Ain Ouksir",
        "Chelalet El Adhaoura",
        "Cheniguel",
        "Tafraout",
        "El Azizia",
        "Maghraoua",
        "Mihoub",
        "Baata",
        "El Omaria",
        "Ouled Brahim",
        "Bir Ben Laabed",
        "El Guelbelkebir",
        "Sedraya",
        "Ksar El Boukhari",
        "M'fatha",
        "Saneg",
        "Draa Esmar",
        "Medea",
        "Tamesguida",
        "Hannacha",
        "Ouamri",
        "Oued Harbil",
        "Boghar",
        "Ouled Antar",
        "Ouled Hellal",
        "Ben Chicao",
        "El Hamdania",
        "Ouzera",
        "Tizi Mahdi",
        "Medjebar",
        "Seghouane",
        "Tletat Ed Douair",
        "Zoubiria",
        "Bouaichoune",
        "Ouled Bouachra",
        "Si Mahdjoub",
        "Bouchrahil",
        "Khams Djouamaa",
        "Sidi Naamane",
        "Djouab",
        "Sidi Zahar",
        "Sidi Ziane",
        "Souagui",
        "Aissaouia",
        "El Haoudane",
        "Mezerana",
        "Tablat"
    ),

    "MOS" => array(
        "Achaacha",
        "Khadra",
        "Nekmaria",
        "Ouled Boughalem",
        "Ain-Nouissy",
        "Fornaka",
        "Hassiane",
        "Ain-Tedles",
        "Oued El Kheir",
        "Sidi Belaattar",
        "Sour",
        "Bouguirat",
        "Safsaf",
        "Sirat",
        "Souaflia",
        "Hassi Mameche",
        "Mazagran",
        "Stidia",
        "Ain-Boudinar",
        "Kheir-Eddine",
        "Sayada",
        "Ain-Sidi Cherif",
        "Mansourah",
        "Mesra",
        "Touahria",
        "Mostaganem",
        "Ouled-Maalah",
        "Sidi Ali",
        "Tazgait",
        "Benabdelmalek Ramdane",
        "Hadjadj",
        "Sidi-Lakhdar"
    ),

    "MSI" => array(
        "Ain El Hadjel",
        "Sidi Hadjeres",
        "Ain El Melh",
        "Ain Fares",
        "Ain Rich",
        "Bir Foda",
        "Sidi M'hamed",
        "Ben Srour",
        "Mohamed Boudiaf",
        "Ouled Slimane",
        "Zarzour",
        "Bou Saada",
        "El Hamel",
        "Oulteme",
        "Chellal",
        "Khettouti Sed-El-Jir",
        "Maarif",
        "Ouled Madhi",
        "Djebel Messaad",
        "Slim",
        "Hammam Dalaa",
        "Ouanougha",
        "Ouled Mansour",
        "Tarmount",
        "El Houamed",
        "Khoubana",
        "M'cif",
        "Ain Khadra",
        "Belaiba",
        "Berhoum",
        "Dehahna",
        "Magra",
        "Medjedel",
        "Menaa",
        "M'sila",
        "Maadid",
        "M'tarfa",
        "Ouled Addi Guebala",
        "Ouled Derradj",
        "Souamaa",
        "Benzouh",
        "Ouled Sidi Brahim",
        "Beni Ilmane",
        "Bouti Sayeh",
        "Sidi Aissa",
        "Sidi Ameur",
        "Tamsa"
    ),

    "MAS" => array(
        "Ain Fares",
        "El Mamounia",
        "Ain Fekan",
        "Ain Frass",
        "Aouf",
        "Benian",
        "Gharrous",
        "Bouhanifia",
        "El Gueitena",
        "Hacine",
        "El Bordj",
        "El Menaouer",
        "Khalouia",
        "Ghriss",
        "Makhda",
        "Maoussa",
        "Matemore",
        "Sidi Boussaid",
        "El Hachem",
        "Nesmot",
        "Zelamta",
        "Mascara",
        "El Ghomri",
        "Ferraguig",
        "Mocta-Douz",
        "Mohammadia",
        "Sedjerara",
        "Sidi Abdelmoumene",
        "Alaimia",
        "Oggaz",
        "Ras El Ain Amirouche",
        "Ain Ferah",
        "Oued El Abtal",
        "Sidi Abdeldjebar",
        "Guerdjoum",
        "Oued Taria",
        "Bou Henni",
        "Chorfa",
        "Sig",
        "Sehailia",
        "Sidi Kada",
        "Tighennif",
        "El Keurt",
        "Froha",
        "Tizi",
        "El Gaada",
        "Zahana"
    ),

    "OUR" => array(
        "El Borma",
        "El Alia",
        "El-Hadjira",
        "Hassi Messaoud",
        "Megarine",
        "Sidi Slimane",
        "N'goussa",
        "Ouargla",
        "Rouissat",
        "Ain Beida",
        "Hassi Ben Abdellah",
        "Sidi Khouiled",
        "Benaceur",
        "M'naguer",
        "Taibet",
        "Blidet Amor",
        "Temacine",
        "Nezla",
        "Tebesbest",
        "Touggourt",
        "Zaouia El Abidia"
    ),

    "ORA" => array(
        "Ain Turk",
        "Bousfer",
        "El Ancor",
        "Mers El Kebir",
        "Arzew",
        "Sidi Ben Yebka",
        "Ain Biya",
        "Bethioua",
        "Marsat El Hadjadj",
        "Bir El Djir",
        "Hassi Ben Okba",
        "Hassi Bounif",
        "Ain Kerma",
        "Boutlelis",
        "Messerghin",
        "El Kerma",
        "Es Senia",
        "Sidi Chami",
        "Ben Freha",
        "Gdyel",
        "Hassi Mefsoukh",
        "Oran",
        "Boufatis",
        "El Braya",
        "Oued Tlelat",
        "Tafraoui"
    ),

    "ELB" => array(
        "Arbaouat",
        "Brezina",
        "Cheguig",
        "Chellala",
        "El Kheither",
        "El Mehara",
        "Ghassoul",
        "Kef El Ahmar",
        "Boualem",
        "El Bnoud",
        "Krakda",
        "Stitten",
        "El Bayadh",
        "Bougtoub",
        "Rogassa",
        "Sidi Tiffour"
    ),

    "ILZ" => array(
        "Bordj El Haouass",
        "Djanet",
        "Illizi",
        "Bordj Omar Driss",
        "Debdeb",
        "In Amenas"
    ),

    "BBA" => array(
        "Ain Taghrout",
        "Tixter",
        "Bir Kasdali",
        "Khelil",
        "Sidi-Embarek",
        "B. B. Arreridj",
        "Belimour",
        "Bordj Ghedir",
        "El Annasseur",
        "Ghailasa",
        "Taglait",
        "Bordj Zemmoura",
        "Ouled Dahmane",
        "Tassamert",
        "Colla",
        "Djaafra",
        "El Main",
        "Tefreg",
        "El Euch",
        "Elhammadia",
        "Ksour",
        "Rabta",
        "Ben Daoud",
        "El M'hir",
        "Haraza",
        "Mansoura",
        "Ouled Sidi-Brahim",
        "El Achir",
        "Hasnaoua",
        "Medjana",
        "Teniet En Nasr",
        "Ain Tesra",
        "Ouled Brahem",
        "Ras El Oued"
    ),

    "BOM" => array(
        "Baghlia",
        "Sidi Daoud",
        "Taourga",
        "Bordj Menaiel",
        "Djinet",
        "Leghata",
        "Zemmouri",
        "Boudouaou",
        "Boudouaou El Bahri",
        "Bouzegza Keddara",
        "El Kharrouba",
        "Ouled Hedadj",
        "Boumerdes",
        "Corso",
        "Tidjelabine",
        "Afir",
        "Ben Choud",
        "Dellys",
        "Chabet El Ameur",
        "Isser",
        "Si Mustapha",
        "Timezrit",
        "Hammedi",
        "Khemis El Khechna",
        "Larbatache",
        "Ouled Moussa",
        "Naciria",
        "Ouled Aissa",
        "Ammal",
        "Beni Amrane",
        "Souk El Had",
        "Thenia"
    ),

    "ETR" => array(
        "Ben M Hidi",
        "Berrihane",
        "Echatt",
        "Asfour",
        "Besbes",
        "Zerizer",
        "Ain Kerma",
        "Bouhadjar",
        "Hammam Beni Salah",
        "Oued Zitoun",
        "Bouteldja",
        "Chefia",
        "Lac Des Oiseaux",
        "Chebaita Mokhtar",
        "Chihani",
        "Drean",
        "El Aioun",
        "El Kala",
        "Raml Souk",
        "Souarekh",
        "Ain El Assel",
        "Bougous",
        "El Tarf",
        "Zitouna"
    ),

    "TIN" => array(
        "Oum El Assel",
        "Tindouf"
    ),

    "TIS" => array(
        "Ammari",
        "Maacem",
        "Sidi Abed",
        "Beni Chaib",
        "Beni Lahcene",
        "Bordj Bounaama",
        "Sidi Slimane",
        "Bordj El Emir Abdelkader",
        "Youssoufia",
        "Khemisti",
        "Layoune",
        "Lardjem",
        "Melaab",
        "Sidi Lantri",
        "Tamellahet",
        "Boucaid",
        "Larbaa",
        "Lazharia",
        "Sidi Boutouchent",
        "Theniet El Had",
        "Ouled Bessam",
        "Tissemsilt"
    ),

    "ELO" => array(
        "Bayadha",
        "Debila",
        "Hassani Abdelkrim",
        "Djamaa",
        "M'rara",
        "Sidi Amrane",
        "Tenedla",
        "El-M'ghaier",
        "Oum Touyour",
        "Sidi Khelil",
        "Still",
        "El-Oued",
        "Kouinine",
        "Guemar",
        "Ourmes",
        "Taghzout",
        "Hassi Khalifa",
        "Trifaoui",
        "Magrane",
        "Sidi Aoun",
        "Mih Ouansa",
        "Oued El Alenda",
        "Hamraia",
        "Reguiba",
        "El Ogla",
        "Nakhla",
        "Robbah",
        "Ben Guecha",
        "Douar El Maa",
        "Taleb Larbi"
    ),

    "KHE" => array(
        "Ain Touila",
        "M'toussa",
        "Babar",
        "Bouhmama",
        "Chelia",
        "M'sara",
        "Yabous",
        "Chechar",
        "Djellal",
        "El Oueldja",
        "Khirane",
        "Baghai",
        "El Hamma",
        "Ensigha",
        "Tamza",
        "Kais",
        "Remila",
        "Taouzianat",
        "Khenchela",
        "El Mahmal",
        "Ouled Rechache"
    ),

    "SOK" => array(
        "Bir Bouhouche",
        "Safel El Ouiden",
        "Zouabi",
        "Haddada",
        "Khedara",
        "Ouled Moumen",
        "M'daourouche",
        "Ragouba",
        "Tiffech",
        "Hanencha",
        "Machroha",
        "Merahna",
        "Ouillen",
        "Sidi Fredj",
        "Ain Zana",
        "Ouled Driss",
        "Oued Kebrit",
        "Oum El Adhaim",
        "Terraguelt",
        "Ain Soltane",
        "Khemissa",
        "Sedrata",
        "Souk Ahras",
        "Drea",
        "Taoura",
        "Zaarouria"
    ),

    "TIP" => array(
        "Ahmer El Ain",
        "Bourkika",
        "Sidi Rached",
        "Ain Tagourait",
        "Bou Haroun",
        "Bou Ismail",
        "Khemisti",
        "Cherchell",
        "Hadjret Ennous",
        "Sidi Ghiles",
        "Sidi Semiane",
        "Beni Mileuk",
        "Damous",
        "Larhat",
        "Douaouda",
        "Fouka",
        "Aghbal",
        "Gouraya",
        "Messelmoun",
        "Hadjout",
        "Merad",
        "Attatba",
        "Chaiba",
        "Kolea",
        "Menaceur",
        "Nador",
        "Sidi-Amar",
        "Tipaza"
    ),

    "MIL" => array(
        "Ain Beida Harriche",
        "El Ayadi Barbes",
        "Bouhatem",
        "Derrahi Bousselah",
        "Ain Mellouk",
        "Chelghoum Laid",
        "Oued Athmenia",
        "Ferdjioua",
        "Yahia Beniguecha",
        "Grarem Gouga",
        "Hamala",
        "Ain Tine",
        "Mila",
        "Sidi Khelifa",
        "Ahmed Rachedi",
        "Oued Endja",
        "Zeghaia",
        "Rouached",
        "Tiberguent",
        "Chigara",
        "Sidi Merouane",
        "Benyahia Abderrahmane",
        "Ouled Khalouf",
        "Tadjenanet",
        "Minar Zarza",
        "Tassadane Haddada",
        "El Mechira",
        "Oued Seguen",
        "Teleghma",
        "Amira Arres",
        "Terrai Bainen",
        "Tassala Lematai"
    ),

    "ADF" => array(
        "Ain-Defla",
        "Ain-Lechiakh",
        "Ain-Soltane",
        "Oued Djemaa",
        "Bathia",
        "Belaas",
        "Hassania",
        "Bir-Ould-Khelifa",
        "Bordj-Emir-Khaled",
        "Tarik-Ibn-Ziad",
        "Boumedfaa",
        "Hoceinia",
        "Bourached",
        "Djelida",
        "Djemaa Ouled Cheikh",
        "Birbouche",
        "Djendel",
        "Oued Chorfa",
        "Ain-Bouyahia",
        "El-Abadia",
        "Tacheta Zegagha",
        "Arib",
        "El-Amra",
        "Mekhatria",
        "El-Attaf",
        "Tiberkanine",
        "Ain-Benian",
        "Ain-Torki",
        "Hammam-Righa",
        "Khemis-Miliana",
        "Sidi-Lakhdar",
        "Ben Allal",
        "Miliana",
        "El-Maine",
        "Rouina",
        "Zeddine",
    ),

    "NAM" => array(
        "Ain Sefra",
        "Tiout",
        "Asla",
        "Ain Ben Khelil",
        "El Biodh",
        "Mecheria",
        "Kasdir",
        "Makmen Ben Amar",
        "Djenienne Bourezg",
        "Moghrar",
        "Naama",
        "Sfissifa"
    ),

    "ATE" => array(
        "Aghlal",
        "Ain Kihal",
        "Ain Tolba",
        "Aoubellil",
        "Ain El Arbaa",
        "Oued Sebbah",
        "Sidi Boumediene",
        "Tamzoura",
        "Ain Temouchent",
        "Sidi Ben Adda",
        "Beni Saf",
        "Emir Abdelkader",
        "Sidi Safi",
        "Bouzedjar",
        "El Amria",
        "El Messaid",
        "Hassi El Ghella",
        "Ouled Boudjemaa",
        "Chaabat El Ham",
        "El Maleh",
        "Ouled Kihal",
        "Terga",
        "Chentouf",
        "Hammam Bou Hadjar",
        "Hassasna",
        "Oued Berkeche",
        "Oulhaca El Gheraba",
        "Sidi Ouriache"
    ),

    "GHA" => array(
        "Berriane",
        "Bounoura",
        "El Atteuf",
        "Dhayet Bendhahoua",
        "El Guerrara",
        "El Meniaa",
        "Hassi Gara",
        "Ghardaia",
        "Hassi Fehal",
        "Mansoura",
        "Metlili",
        "Sebseb",
        "Zelfana"
    ),

    "REL" => array(
        "Ain-Tarek",
        "Had Echkalla",
        "Ammi Moussa",
        "El Hassi",
        "El Ouldja",
        "Ouled Aiche",
        "Djidiouia",
        "Hamri",
        "Ouled Sidi Mihoub",
        "El H'madna",
        "Oued El Djemaa",
        "Belaassel Bouzagza",
        "El-Matmar",
        "Sidi Khettab",
        "Sidi M'hamed Benaouda",
        "El-Guettar",
        "Mazouna",
        "Mendes",
        "Oued Essalem",
        "Sidi Lazreg",
        "Lahlef",
        "Merdja Sidi Abed",
        "Ouarizane",
        "Oued-Rhiou",
        "Ramka",
        "Souk El Had",
        "Bendaoud",
        "Relizane",
        "Beni Zentis",
        "Mediouna",
        "Sidi M'hamed Benali",
        "Ain Rahma",
        "Kalaa",
        "Sidi Saada",
        "Yellel",
        "Beni Dergoun",
        "Dar Ben Abdelah",
        "Zemmoura"
    ),

);